name: Ramda bumper
on:
  workflow_dispatch
jobs:
  bump-ramda:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Setup'
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn
      - run: yarn upgrade ramda@latest
      - name: 'Create PR'
        uses: peter-evans/create-pull-request@v3
        with:
          branch: bump-ramda
          commit-message: Bump ramda
          delete-branch: true
          title: Automagic bump
