name: Ramda bumper
on:
  workflow_dispatch
jobs:
  bump-ramda:
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Setup'
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn
      - run: yarn update ramda
      - name: 'Commit'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional, but recommended
          # Defaults to "Apply automatic changes"
          commit_message: "Bump ramda"

          # Optional branch name where commit should be pushed to.
          # Defaults to the current branch.
          # this should probably be generated, somehow
          branch: bump-ramda

          # Optional commit user and author settings
          commit_user_name: Mr bumper # defaults to "GitHub Actions"
          commit_user_email: pontus.hjortskog@meltwater.org # defaults to "actions@github.com"
          commit_author: Pontus <pontus.hjortskog@meltwater.org> # defaults to author of the commit that triggered the run

          # Optional. Disable dirty check and always try to create a commit and push
          # skip_dirty_check: true

          # Optional. Skip internal call to `git fetch`
          # skip_fetch: true
      - name: 'Create PR'
        uses: peter-evans/create-pull-request@v3
        with:
          branch: ramda-bump
